var FlagData = [
    { name: 'Afghanistan', flag: 'af.svg', code: 'AF', dial_code: '+93' },
    {
        name: 'Åland Islands',
        flag: 'ac.svg',
        code: 'AX',
        dial_code: '+358',
    },
    { name: 'Albania', flag: 'al.svg', code: 'AL', dial_code: '+355' },
    { name: 'Algeria', flag: 'dz.svg', code: 'DZ', dial_code: '+213' },
    {
        name: 'American Samoa',
        flag: 'as.svg',
        code: 'AS',
        dial_code: '+1684',
    },
    { name: 'Andorra', flag: 'ad.svg', code: 'AD', dial_code: '+376' },
    { name: 'Angola', flag: 'ao.svg', code: 'AO', dial_code: '+244' },
    { name: 'Anguilla', flag: 'ai.svg', code: 'AI', dial_code: '+1264' },
    { name: 'Antarctica', flag: 'aq.svg', code: 'AQ', dial_code: '+672' },
    {
        name: 'Antigua and Barbuda',
        flag: 'ag.svg',
        code: 'AG',
        dial_code: '+1268',
    },
    { name: 'Argentina', flag: 'ar.svg', code: 'AR', dial_code: '+54' },
    { name: 'Armenia', flag: 'am.svg', code: 'AM', dial_code: '+374' },
    { name: 'Aruba', flag: 'aw.svg', code: 'AW', dial_code: '+297' },
    { name: 'Australia', flag: 'au.svg', code: 'AU', dial_code: '+61' },
    { name: 'Austria', flag: 'at.svg', code: 'AT', dial_code: '+43' },
    { name: 'Azerbaijan', flag: 'az.svg', code: 'AZ', dial_code: '+994' },
    { name: 'Bahamas', flag: 'bs.svg', code: 'BS', dial_code: '+1242' },
    { name: 'Bahrain', flag: 'bh.svg', code: 'BH', dial_code: '+973' },
    { name: 'Bangladesh', flag: 'bd.svg', code: 'BD', dial_code: '+880' },
    { name: 'Barbados', flag: 'bb.svg', code: 'BB', dial_code: '+1246' },
    { name: 'Belarus', flag: 'by.svg', code: 'BY', dial_code: '+375' },
    { name: 'Belgium', flag: 'be.svg', code: 'BE', dial_code: '+32' },
    { name: 'Belize', flag: 'bz.svg', code: 'BZ', dial_code: '+501' },
    { name: 'Benin', flag: 'bj.svg', code: 'BJ', dial_code: '+229' },
    { name: 'Bermuda', flag: 'bm.svg', code: 'BM', dial_code: '+1441' },
    { name: 'Bhutan', flag: 'bt.svg', code: 'BT', dial_code: '+975' },
    {
        name: 'Bolivia, Plurinational State of bolivia',
        flag: 'bo.svg',
        code: 'BO',
        dial_code: '+591',
    },
    {
        name: 'Bosnia and Herzegovina',
        flag: 'ba.svg',
        code: 'BA',
        dial_code: '+387',
    },
    { name: 'Botswana', flag: 'bw.svg', code: 'BW', dial_code: '+267' },
    { name: 'Bouvet Island', flag: 'bv.svg', code: 'BV', dial_code: '+47' },
    { name: 'Brazil', flag: 'br.svg', code: 'BR', dial_code: '+55' },
    {
        name: 'British Indian Ocean Territory',
        flag: 'io.svg',
        code: 'IO',
        dial_code: '+246',
    },
    {
        name: 'Brunei Darussalam',
        flag: 'bn.svg',
        code: 'BN',
        dial_code: '+673',
    },
    { name: 'Bulgaria', flag: 'bg.svg', code: 'BG', dial_code: '+359' },
    { name: 'Burkina Faso', flag: 'bf.svg', code: 'BF', dial_code: '+226' },
    { name: 'Burundi', flag: 'bi.svg', code: 'BI', dial_code: '+257' },
    { name: 'Cambodia', flag: 'kh.svg', code: 'KH', dial_code: '+855' },
    { name: 'Cameroon', flag: 'cm.svg', code: 'CM', dial_code: '+237' },
    { name: 'Canada', flag: 'ca.svg', code: 'CA', dial_code: '+1' },
    { name: 'Cape Verde', flag: 'cv.svg', code: 'CV', dial_code: '+238' },
    {
        name: 'Cayman Islands',
        flag: 'ky.svg',
        code: 'KY',
        dial_code: '+345',
    },
    {
        name: 'Central African Republic',
        flag: 'cf.svg',
        code: 'CF',
        dial_code: '+236',
    },
    { name: 'Chad', flag: 'td.svg', code: 'TD', dial_code: '+235' },
    { name: 'Chile', flag: 'cl.svg', code: 'CL', dial_code: '+56' },
    { name: 'China', flag: 'cn.svg', code: 'CN', dial_code: '+86' },
    {
        name: 'Christmas Island',
        flag: 'cx.svg',
        code: 'CX',
        dial_code: '+61',
    },
    {
        name: 'Cocos (Keeling) Islands',
        flag: 'cc.svg',
        code: 'CC',
        dial_code: '+61',
    },
    { name: 'Colombia', flag: 'co.svg', code: 'CO', dial_code: '+57' },
    { name: 'Comoros', flag: 'km.svg', code: 'KM', dial_code: '+269' },
    { name: 'Congo', flag: 'cg.svg', code: 'CG', dial_code: '+242' },
    {
        name: 'Congo, The Democratic Republic of the Congo',
        flag: 'cd.svg',
        code: 'CD',
        dial_code: '+243',
    },
    { name: 'Cook Islands', flag: 'ck.svg', code: 'CK', dial_code: '+682' },
    { name: 'Costa Rica', flag: 'cr.svg', code: 'CR', dial_code: '+506' },
    {
        name: "Cote d'Ivoire",
        flag: 'ci.svg',
        code: 'CI',
        dial_code: '+225',
    },
    { name: 'Croatia', flag: 'hr.svg', code: 'HR', dial_code: '+385' },
    { name: 'Cuba', flag: 'cu.svg', code: 'CU', dial_code: '+53' },
    { name: 'Cyprus', flag: 'cy.svg', code: 'CY', dial_code: '+357' },
    {
        name: 'Czech Republic',
        flag: 'cz.svg',
        code: 'CZ',
        dial_code: '+420',
    },
    { name: 'Denmark', flag: 'dk.svg', code: 'DK', dial_code: '+45' },
    { name: 'Djibouti', flag: 'dj.svg', code: 'DJ', dial_code: '+253' },
    { name: 'Dominica', flag: 'dm.svg', code: 'DM', dial_code: '+1767' },
    {
        name: 'Dominican Republic',
        flag: 'do.svg',
        code: 'DO',
        dial_code: '+1849',
    },
    { name: 'Ecuador', flag: 'ec.svg', code: 'EC', dial_code: '+593' },
    { name: 'Egypt', flag: 'eg.svg', code: 'EG', dial_code: '+20' },
    { name: 'El Salvador', flag: 'sv.svg', code: 'SV', dial_code: '+503' },
    {
        name: 'Equatorial Guinea',
        flag: 'gq.svg',
        code: 'GQ',
        dial_code: '+240',
    },
    { name: 'Eritrea', flag: 'er.svg', code: 'ER', dial_code: '+291' },
    { name: 'Estonia', flag: 'ee.svg', code: 'EE', dial_code: '+372' },
    { name: 'Ethiopia', flag: 'et.svg', code: 'ET', dial_code: '+251' },
    {
        name: 'Falkland Islands (Malvinas)',
        flag: 'fk.svg',
        code: 'FK',
        dial_code: '+500',
    },
    {
        name: 'Faroe Islands',
        flag: 'fo.svg',
        code: 'FO',
        dial_code: '+298',
    },
    { name: 'Fiji', flag: 'fj.svg', code: 'FJ', dial_code: '+679' },
    { name: 'Finland', flag: 'fi.svg', code: 'FI', dial_code: '+358' },
    { name: 'France', flag: 'fr.svg', code: 'FR', dial_code: '+33' },
    {
        name: 'French Guiana',
        flag: 'gf.svg',
        code: 'GF',
        dial_code: '+594',
    },
    {
        name: 'French Polynesia',
        flag: 'pf.svg',
        code: 'PF',
        dial_code: '+689',
    },
    {
        name: 'French Southern Territories',
        flag: 'tf.svg',
        code: 'TF',
        dial_code: '+262',
    },
    { name: 'Gabon', flag: 'ga.svg', code: 'GA', dial_code: '+241' },
    { name: 'Gambia', flag: 'gm.svg', code: 'GM', dial_code: '+220' },
    { name: 'Georgia', flag: 'ge.svg', code: 'GE', dial_code: '+995' },
    { name: 'Germany', flag: 'de.svg', code: 'DE', dial_code: '+49' },
    { name: 'Ghana', flag: 'gh.svg', code: 'GH', dial_code: '+233' },
    { name: 'Gibraltar', flag: 'gi.svg', code: 'GI', dial_code: '+350' },
    {
        name: 'Greece',
        flag: 'gr.svg',
        code: 'GR',
        dial_code: '+30',
        nativeName: 'Ελληνικά'
    },
    { name: 'Greenland', flag: 'gl.svg', code: 'GL', dial_code: '+299' },
    { name: 'Grenada', flag: 'gd.svg', code: 'GD', dial_code: '+1473' },
    { name: 'Guadeloupe', flag: 'gp.svg', code: 'GP', dial_code: '+590' },
    { name: 'Guam', flag: 'gu.svg', code: 'GU', dial_code: '+1671' },
    { name: 'Guatemala', flag: 'gt.svg', code: 'GT', dial_code: '+502' },
    { name: 'Guernsey', flag: 'gg.svg', code: 'GG', dial_code: '+44' },
    { name: 'Guinea', flag: 'gn.svg', code: 'GN', dial_code: '+224' },
    {
        name: 'Guinea-Bissau',
        flag: 'gw.svg',
        code: 'GW',
        dial_code: '+245',
    },
    { name: 'Guyana', flag: 'gy.svg', code: 'GY', dial_code: '+592' },
    { name: 'Haiti', flag: 'ht.svg', code: 'HT', dial_code: '+509' },
    {
        name: 'Heard Island and Mcdonald Islands',
        flag: 'hm.svg',
        code: 'HM',
        dial_code: '+672',
    },
    {
        name: 'Holy See (Vatican City State)',
        flag: 'va.svg',
        code: 'VA',
        dial_code: '+379',
    },
    { name: 'Honduras', flag: 'hn.svg', code: 'HN', dial_code: '+504' },
    { name: 'Hong Kong', flag: 'hk.svg', code: 'HK', dial_code: '+852' },
    { name: 'Hungary', flag: 'hu.svg', code: 'HU', dial_code: '+36' },
    { name: 'Iceland', flag: 'is.svg', code: 'IS', dial_code: '+354' },
    { name: 'India', flag: 'in.svg', code: 'IN', dial_code: '+91' },
    { name: 'Indonesia', flag: 'id.svg', code: 'ID', dial_code: '+62' },
    {
        name: 'Iran, Islamic Republic of Persian Gulf',
        flag: 'ir.svg',
        code: 'IR',
        dial_code: '+98',
    },
    { name: 'Iraq', flag: 'iq.svg', code: 'IQ', dial_code: '+964' },
    { name: 'Ireland', flag: 'ie.svg', code: 'IE', dial_code: '+353' },
    { name: 'Isle of Man', flag: 'im.svg', code: 'IM', dial_code: '+44' },
    { name: 'Israel', flag: 'il.svg', code: 'IL', dial_code: '+972' },
    { name: 'Italy', flag: 'it.svg', code: 'IT', dial_code: '+39' },
    { name: 'Jamaica', flag: 'jm.svg', code: 'JM', dial_code: '+1876' },
    { name: 'Japan', flag: 'jp.svg', code: 'JP', dial_code: '+81' },
    { name: 'Jersey', flag: 'je.svg', code: 'JE', dial_code: '+44' },
    { name: 'Jordan', flag: 'jo.svg', code: 'JO', dial_code: '+962' },
    { name: 'Kazakhstan', flag: 'kz.svg', code: 'KZ', dial_code: '+7' },
    { name: 'Kenya', flag: 'ke.svg', code: 'KE', dial_code: '+254' },
    { name: 'Kiribati', flag: 'ki.svg', code: 'KI', dial_code: '+686' },
    {
        name: "Korea, Democratic People's Republic of Korea",
        flag: 'kp.svg',
        code: 'KP',
        dial_code: '+850',
    },
    {
        name: 'Korea, Republic of South Korea',
        flag: 'kr.svg',
        code: 'KR',
        dial_code: '+82',
    },
    { name: 'Kosovo', flag: 'xk.svg', code: 'XK', dial_code: '+383' },
    { name: 'Kuwait', flag: 'kw.svg', code: 'KW', dial_code: '+965' },
    { name: 'Kyrgyzstan', flag: 'kg.svg', code: 'KG', dial_code: '+996' },
    { name: 'Laos', flag: 'la.svg', code: 'LA', dial_code: '+856' },
    { name: 'Latvia', flag: 'lv.svg', code: 'LV', dial_code: '+371' },
    { name: 'Lebanon', flag: 'lb.svg', code: 'LB', dial_code: '+961' },
    { name: 'Lesotho', flag: 'ls.svg', code: 'LS', dial_code: '+266' },
    { name: 'Liberia', flag: 'lr.svg', code: 'LR', dial_code: '+231' },
    {
        name: 'Libyan Arab Jamahiriya',
        flag: 'ly.svg',
        code: 'LY',
        dial_code: '+218',
    },
    {
        name: 'Liechtenstein',
        flag: 'li.svg',
        code: 'LI',
        dial_code: '+423',
    },
    { name: 'Lithuania', flag: 'lt.svg', code: 'LT', dial_code: '+370' },
    { name: 'Luxembourg', flag: 'lu.svg', code: 'LU', dial_code: '+352' },
    { name: 'Macao', flag: 'mo.svg', code: 'MO', dial_code: '+853' },
    { name: 'Macedonia', flag: 'mk.svg', code: 'MK', dial_code: '+389' },
    { name: 'Madagascar', flag: 'mg.svg', code: 'MG', dial_code: '+261' },
    { name: 'Malawi', flag: 'mw.svg', code: 'MW', dial_code: '+265' },
    { name: 'Malaysia', flag: 'my.svg', code: 'MY', dial_code: '+60' },
    { name: 'Maldives', flag: 'mv.svg', code: 'MV', dial_code: '+960' },
    { name: 'Mali', flag: 'ml.svg', code: 'ML', dial_code: '+223' },
    { name: 'Malta', flag: 'mt.svg', code: 'MT', dial_code: '+356' },
    {
        name: 'Marshall Islands',
        flag: 'mh.svg',
        code: 'MH',
        dial_code: '+692',
    },
    { name: 'Martinique', flag: 'mq.svg', code: 'MQ', dial_code: '+596' },
    { name: 'Mauritania', flag: 'mr.svg', code: 'MR', dial_code: '+222' },
    { name: 'Mauritius', flag: 'mu.svg', code: 'MU', dial_code: '+230' },
    { name: 'Mayotte', flag: 'yt.svg', code: 'YT', dial_code: '+262' },
    { name: 'Mexico', flag: 'mx.svg', code: 'MX', dial_code: '+52' },
    {
        name: 'Micronesia, Federated States of Micronesia',
        flag: 'fm.svg',
        code: 'FM',
        dial_code: '+691',
    },
    { name: 'Moldova', flag: 'md.svg', code: 'MD', dial_code: '+373' },
    { name: 'Monaco', flag: 'mc.svg', code: 'MC', dial_code: '+377' },
    { name: 'Mongolia', flag: 'mn.svg', code: 'MN', dial_code: '+976' },
    { name: 'Montenegro', flag: 'me.svg', code: 'ME', dial_code: '+382' },
    { name: 'Montserrat', flag: 'ms.svg', code: 'MS', dial_code: '+1664' },
    { name: 'Morocco', flag: 'ma.svg', code: 'MA', dial_code: '+212' },
    { name: 'Mozambique', flag: 'mz.svg', code: 'MZ', dial_code: '+258' },
    { name: 'Myanmar', flag: 'mm.svg', code: 'MM', dial_code: '+95' },
    { name: 'Namibia', flag: 'na.svg', code: 'NA', dial_code: '+264' },
    { name: 'Nauru', flag: 'nr.svg', code: 'NR', dial_code: '+674' },
    { name: 'Nepal', flag: 'np.svg', code: 'NP', dial_code: '+977' },
    { name: 'Netherlands', flag: 'nl.svg', code: 'NL', dial_code: '+31' },
    {
        name: 'Netherlands Antilles',
        flag: 'cw.svg',
        code: 'AN',
        dial_code: '+599',
    },
    {
        name: 'New Caledonia',
        flag: 'nc.svg',
        code: 'NC',
        dial_code: '+687',
    },
    { name: 'New Zealand', flag: 'nz.svg', code: 'NZ', dial_code: '+64' },
    { name: 'Nicaragua', flag: 'ni.svg', code: 'NI', dial_code: '+505' },
    { name: 'Niger', flag: 'ne.svg', code: 'NE', dial_code: '+227' },
    { name: 'Nigeria', flag: 'ng.svg', code: 'NG', dial_code: '+234' },
    { name: 'Niue', flag: 'nu.svg', code: 'NU', dial_code: '+683' },
    {
        name: 'Norfolk Island',
        flag: 'nf.svg',
        code: 'NF',
        dial_code: '+672',
    },
    {
        name: 'Northern Mariana Islands',
        flag: 'mp.svg',
        code: 'MP',
        dial_code: '+1670',
    },
    { name: 'Norway', flag: 'no.svg', code: 'NO', dial_code: '+47' },
    { name: 'Oman', flag: 'om.svg', code: 'OM', dial_code: '+968' },
    { name: 'Pakistan', flag: 'pk.svg', code: 'PK', dial_code: '+92' },
    { name: 'Palau', flag: 'pw.svg', code: 'PW', dial_code: '+680' },
    {
        name: 'Palestinian Territory, Occupied',
        flag: 'ps.svg',
        code: 'PS',
        dial_code: '+970',
    },
    { name: 'Panama', flag: 'pa.svg', code: 'PA', dial_code: '+507' },
    {
        name: 'Papua New Guinea',
        flag: 'pg.svg',
        code: 'PG',
        dial_code: '+675',
    },
    { name: 'Paraguay', flag: 'py.svg', code: 'PY', dial_code: '+595' },
    { name: 'Peru', flag: 'pe.svg', code: 'PE', dial_code: '+51' },
    { name: 'Philippines', flag: 'ph.svg', code: 'PH', dial_code: '+63' },
    { name: 'Pitcairn', flag: 'pn.svg', code: 'PN', dial_code: '+64' },
    { name: 'Poland', flag: 'pl.svg', code: 'PL', dial_code: '+48' },
    { name: 'Portugal', flag: 'pt.svg', code: 'PT', dial_code: '+351' },
    { name: 'Puerto Rico', flag: 'pr.svg', code: 'PR', dial_code: '+1939' },
    { name: 'Qatar', flag: 'qa.svg', code: 'QA', dial_code: '+974' },
    { name: 'Romania', flag: 'ro.svg', code: 'RO', dial_code: '+40' },
    { name: 'Russia', flag: 'ru.svg', code: 'RU', dial_code: '+7' },
    { name: 'Rwanda', flag: 'rw.svg', code: 'RW', dial_code: '+250' },
    { name: 'Reunion', flag: 're.svg', code: 'RE', dial_code: '+262' },
    {
        name: 'Saint Barthelemy',
        flag: 'bl.svg',
        code: 'BL',
        dial_code: '+590',
    },
    {
        name: 'Saint Helena, Ascension and Tristan Da Cunha',
        flag: 'sh.svg',
        code: 'SH',
        dial_code: '+290',
    },
    {
        name: 'Saint Kitts and Nevis',
        flag: 'kn.svg',
        code: 'KN',
        dial_code: '+1869',
    },
    { name: 'Saint Lucia', flag: 'lc.svg', code: 'LC', dial_code: '+1758' },
    { name: 'Saint Martin', flag: 'mf.svg', code: 'MF', dial_code: '+590' },
    {
        name: 'Saint Pierre and Miquelon',
        flag: 'pm.svg',
        code: 'PM',
        dial_code: '+508',
    },
    {
        name: 'Saint Vincent and the Grenadines',
        flag: 'vc.svg',
        code: 'VC',
        dial_code: '+1784',
    },
    { name: 'Samoa', flag: 'ws.svg', code: 'WS', dial_code: '+685' },
    { name: 'San Marino', flag: 'sm.svg', code: 'SM', dial_code: '+378' },
    {
        name: 'Sao Tome and Principe',
        flag: 'st.svg',
        code: 'ST',
        dial_code: '+239',
    },
    { name: 'Saudi Arabia', flag: 'sa.svg', code: 'SA', dial_code: '+966' },
    { name: 'Senegal', flag: 'sn.svg', code: 'SN', dial_code: '+221' },
    { name: 'Serbia', flag: 'rs.svg', code: 'RS', dial_code: '+381' },
    { name: 'Seychelles', flag: 'sc.svg', code: 'SC', dial_code: '+248' },
    { name: 'Sierra Leone', flag: 'sl.svg', code: 'SL', dial_code: '+232' },
    { name: 'Singapore', flag: 'sg.svg', code: 'SG', dial_code: '+65' },
    { name: 'Slovakia', flag: 'sk.svg', code: 'SK', dial_code: '+421' },
    { name: 'Slovenia', flag: 'si.svg', code: 'SI', dial_code: '+386' },
    {
        name: 'Solomon Islands',
        flag: 'sb.svg',
        code: 'SB',
        dial_code: '+677',
    },
    { name: 'Somalia', flag: 'so.svg', code: 'SO', dial_code: '+252' },
    { name: 'South Africa', flag: 'za.svg', code: 'ZA', dial_code: '+27' },
    { name: 'South Sudan', flag: 'ss.svg', code: 'SS', dial_code: '+211' },
    {
        name: 'South Georgia and the South Sandwich Islands',
        flag: 'gs.svg',
        code: 'GS',
        dial_code: '+500',
    },
    { name: 'Spain', flag: 'es.svg', code: 'ES', dial_code: '+34' },
    { name: 'Sri Lanka', flag: 'lk.svg', code: 'LK', dial_code: '+94' },
    { name: 'Sudan', flag: 'sd.svg', code: 'SD', dial_code: '+249' },
    { name: 'Suriname', flag: 'sr.svg', code: 'SR', dial_code: '+597' },
    {
        name: 'Svalbard and Jan Mayen',
        flag: 'sj.svg',
        code: 'SJ',
        dial_code: '+47',
    },
    { name: 'Eswatini', flag: 'sz.svg', code: 'SZ', dial_code: '+268' },
    { name: 'Sweden', flag: 'se.svg', code: 'SE', dial_code: '+46' },
    { name: 'Switzerland', flag: 'ch.svg', code: 'CH', dial_code: '+41' },
    {
        name: 'Syrian Arab Republic',
        flag: 'sy.svg',
        code: 'SY',
        dial_code: '+963',
    },
    { name: 'Taiwan', flag: 'tw.svg', code: 'TW', dial_code: '+886' },
    { name: 'Tajikistan', flag: 'tj.svg', code: 'TJ', dial_code: '+992' },
    {
        name: 'Tanzania, United Republic of Tanzania',
        flag: 'tz.svg',
        code: 'TZ',
        dial_code: '+255',
    },
    { name: 'Thailand', flag: 'th.svg', code: 'TH', dial_code: '+66' },
    { name: 'Timor-Leste', flag: 'tl.svg', code: 'TL', dial_code: '+670' },
    { name: 'Togo', flag: 'tg.svg', code: 'TG', dial_code: '+228' },
    { name: 'Tokelau', flag: 'tk.svg', code: 'TK', dial_code: '+690' },
    { name: 'Tonga', flag: 'to.svg', code: 'TO', dial_code: '+676' },
    {
        name: 'Trinidad and Tobago',
        flag: 'tt.svg',
        code: 'TT',
        dial_code: '+1868',
    },
    { name: 'Tunisia', flag: 'tn.svg', code: 'TN', dial_code: '+216' },
    { name: 'Turkey', flag: 'tr.svg', code: 'TR', dial_code: '+90' },
    { name: 'Turkmenistan', flag: 'tm.svg', code: 'TM', dial_code: '+993' },
    {
        name: 'Turks and Caicos Islands',
        flag: 'tc.svg',
        code: 'TC',
        dial_code: '+1649',
    },
    { name: 'Tuvalu', flag: 'tv.svg', code: 'TV', dial_code: '+688' },
    { name: 'Uganda', flag: 'ug.svg', code: 'UG', dial_code: '+256' },
    { name: 'Ukraine', flag: 'ua.svg', code: 'UA', dial_code: '+380' },
    {
        name: 'United Arab Emirates',
        flag: 'ae.svg',
        code: 'AE',
        dial_code: '+971',
    },
    {
        name: 'United Kingdom',
        flag: 'gb.svg',
        code: 'GB',
        dial_code: '+44',
        nativeName: 'English'
    },
    { name: 'United States', flag: 'us.svg', code: 'US', dial_code: '+1' },
    { name: 'Uruguay', flag: 'uy.svg', code: 'UY', dial_code: '+598' },
    { name: 'Uzbekistan', flag: 'uz.svg', code: 'UZ', dial_code: '+998' },
    { name: 'Vanuatu', flag: 'vu.svg', code: 'VU', dial_code: '+678' },
    {
        name: 'Venezuela, Bolivarian Republic of Venezuela',
        flag: 've.svg',
        code: 'VE',
        dial_code: '+58',
    },
    { name: 'Vietnam', flag: 'vn.svg', code: 'VN', dial_code: '+84' },
    {
        name: 'Virgin Islands, British',
        flag: 'vg.svg',
        code: 'VG',
        dial_code: '+1284',
    },
    {
        name: 'Virgin Islands, U.S.',
        flag: 'vi.svg',
        code: 'VI',
        dial_code: '+1340',
    },
    {
        name: 'Wallis and Futuna',
        flag: 'wf.svg',
        code: 'WF',
        dial_code: '+681',
    },
    { name: 'Yemen', flag: 'ye.svg', code: 'YE', dial_code: '+967' },
    { name: 'Zambia', flag: 'zm.svg', code: 'ZM', dial_code: '+260' },
    { name: 'Zimbabwe', flag: 'zw.svg', code: 'ZW', dial_code: '+263' },
];

export default FlagData;
